# Generated by Django 3.2.6 on 2021-08-24 00:42

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_author_book_authors'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='NewGinIndex'),
        ),
    ]
